package com.example.tasteadventure.presentation.util

sealed class AppScreen(val route: String) {
    object HomeScreen : AppScreen(ConstantAppScreenName.HOME_SCREEN)
    object DetailsScreen : AppScreen(ConstantAppScreenName.DETAILS_SCREEN)

}


object ConstantAppScreenName {
    const val HOME_ROUTE = "home"
    const val LOCATION_ROUTE = "location"
    const val PROFILE_ROUTE = "profile"
    const val NOTIFICATION_ROUTE = "notification"
    const val CART_SCREEN = "cart_screen"
    const val PAYMENT_SCREEN = "payment_screen"

    const val HOME_SCREEN = "home_screen"
    const val DETAILS_SCREEN = "details_screen"
    const val INTRO_SCREEN = "intro_screen"
    const val LOGIN_SCREEN = "login_screen"
    const val SPLASH_SCREEN = "splash_screen"
    const val RESET_PASSWORD_SCREEN = "reset_password_screen"
    const val REGISTER_SCREEN = "register_screen"
    const val TERMS_AND_CONDITION_SCREEN = "terms_and_condition"
    const val NOTIFICATION_SCREEN = "notification_screen"
    const val PLACE_A_BID_SCREEN = "place_a_bid_screen"
    const val VENDOR_REVIEW_SCREEN = "vendor_review_screen"
    const val BRAND_LIST_SCREEN = "brand_list_screen"
    const val FULL_SCREEN_IMAGE = "full_screen_image"
    const val PRODUCTS_LIST_SCREEN = "products_list_screen"
    const val VENDOR_PRODUCTS_LIST_SCREEN = "vendor_products_list_screen"
    const val MY_ORDER_SCREEN = "my_order_screen"
    const val ORDER_DETAILS_SCREEN = "order_detail_screen"
    const val FILTER_SCREEN = "filter_screen"
    const val ADD_REVIEW_SCREEN = "add_review_screen"
    const val PAYMENT_OPTION_SCREEN = "payment_option_screen"
    const val MY_ADDRESS_SCREEN = "my_address_screen"
    const val PRODUCT_DETAILS_SCREEN = "product_details_screen"
    const val MAKE_AN_OFFER_SCREEN = "make_an_offer_screen"
    const val VENDOR_DETAILS_SCREEN = "vendor_details_screen"
    const val SEARCH_PRODUCT_SCREEN = "search_product_screen"
    const val CART_CHECKOUT_SCREEN = "cart_checkout_screen"
    const val PAYMENT_SUCCESS_SCREEN = "payment_success_screen"
    const val ADD_NEW_ADDRESS_SCREEN = "add_new_address_screen"
    const val HELP_AND_SUPPORT_SCREEN = "help_and_suupport_screen"
    const val FREQUENTLY_ASK_QUE_SCREEN = "frequently_ask_que_screen"
    const val CONTACT_US_SCREEN = "contact_us_screen"
    const val EDIT_PROFILE_SCREEN = "edit_profile_screen"
    const val CHANGE_PASS_SCREEN = "change_pass_screen"
    const val MY_OFFER_SCREEN = "my_offer_screen"
    const val MY_BIDS_SCREEN = "my_bids_screen"
    const val EDIT_STORE_SCREEN = "edit_store_screen"
    const val SELL_PRODUCT_SCREEN = "sell_product_screen"
    const val PRODUCT_SEARCH_SCREEN = "product_search_screen"
    const val ORDER_MANAGEMENT_SCREEN = "order_management_screen"
    const val VIEW_ORDER_SCREEN = "view_order_screen"
    const val SEE_REVIEW_SCREEN = "see_review_screen"
    const val ADD_NEW_PRODUCT_SCREEN = "add_new_product_screen"
    const val BIDS_MANAGEMENT_SCREEN = "bids_management_screen"
    const val INVENTORY_MANAGEMENT_SCREEN = "inventory_management_screen"
    const val OFFERED_PRODUCT_SCREEN = "offer_product_screen"
    const val BIDS_DETAILS_SCREEN = "bids_details_screen"
    const val USER_BIDS_DETAILS_SCREEN = "user_bids_details_screen"
    const val STORE_MANAGEMENT_SCREEN = "store_management_screen"
    const val EDIT_ACCOUNT_DETAILS_SCREEN = "edit_account_details_screen"
    const val PRODUCT_MANAGEMENT_SCREEN = "product_management_screen"
    const val AUCTION_PRODUCT_SCREEN = "auction_product_screen"
    const val ADD_PRODUCT_SCREEN = "add_product_screen"
    const val PRODUCT_MANAGEMENT_DETAILS_SCREEN = "product_management_details_screen"
    const val PRODUCT_MANAGEMENT_FILTER_SCREEN = "product_management_filter_screen"
    const val OFFERED_RECEIVED_SCREEN = "offered_received_screen"
    const val OFFERED_DETAILS_SCREEN = "offered_details_screen"
    const val PROFILE_SCREEN = "profile_screen"
    const val FILTER_BRAND_SCREEN = "filter_brand_screen"
    const val FILTER_VENDOR_LIST_SCREEN = "filter_vendor_screen"


}